# Generated by Django 3.0.4 on 2020-03-22 16:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('title', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('vendor', models.CharField(max_length=250)),
                ('purchase_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('serial', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='techs.Tech')),
            ],
        ),
    ]
